### PR TITLE
add docker image for reMarkable

### PR DESCRIPTION
**Pull request by pazos**
untested for the sake of my poor bandwidth :+1:

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/virdevenv/47)

### CODE REVIEW

**Comment by Frenzie** [comment]
It builds; pushing as we speak.

**Comment by Frenzie** [comment]
Build successful.

https://gitlab.com/koreader/nightly-builds/-/jobs/430363412
http://build.koreader.rocks/download/nightly/v2020.01-21-g1177baa_2020-02-08/

It'll still have to be added here: https://github.com/koreader/koreader-misc/blob/68a1fa175b94cd807c440fbdf91db878f2a913a0/nightswatcher/nightswatcher.py#L131-L136

@tcrs is everything in working order with the build?

**Comment by tcrs** [comment]
I've just done a fresh install of koreader from that binary, all looks good to me :)

**Comment by Frenzie** [comment]
Alright, then I'll add it to the OTA list… although probably not tonight.

**Comment by Frenzie** [comment]
@tcrs You can now test OTA updating. ;-)

**Comment by tcrs** [comment]
I've just updated from ota.koreader.rocks and all looks good :). Thanks!

**Pull request merged**
