### PR TITLE
appimage: fix user

### PR DESCRIPTION
**Pull request by Frenzie**
This change is [Reviewable](https://reviewable.io/reviews/koreader/virdevenv/91)

### CODE REVIEW

**Comment by benoit-pierre** [comment]
I should have used:
```
ARG REGISTRY=docker.io
FROM $REGISTRY/koreader/kobase:0.3.1-20.04 AS base

FROM base AS build

RUN sudo apt-get update
RUN sudo apt-get upgrade -y
RUN sudo apt-get install -y --no-install-recommends libsndio7.0
RUN sudo apt-get clean
RUN sudo rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

FROM base
COPY --from=build / /
```

So it inherits from the kobase.

**Comment by benoit-pierre** [comment]
Diff for Dockerfile:
```diff
 koappimage/Dockerfile | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git i/koappimage/Dockerfile w/koappimage/Dockerfile
index b10213b..4b27b09 100644
--- i/koappimage/Dockerfile
+++ w/koappimage/Dockerfile
@@ -1,7 +1,7 @@
 ARG REGISTRY=docker.io
-FROM scratch AS base
+FROM $REGISTRY/koreader/kobase:0.3.1-20.04 AS base
 
-FROM $REGISTRY/koreader/kobase:0.3.1-20.04 AS build
+FROM base AS build
 
 RUN sudo apt-get update
 RUN sudo apt-get upgrade -y
```

**Comment by benoit-pierre** [comment]
Same for `baseimage-clang`… I'll make a PR for that one.

**Comment by Frenzie** [comment]
Presumably that means these lines were accidentally left behind?
https://github.com/koreader/virdevenv/blob/dbf52c4c096228331ee151ad4c86202c8b6dadad/docker/ubuntu/kokobo/Dockerfile#L4-L6

**Comment by benoit-pierre** [comment]
Add a `USER root` in the build stage so there's no need for sudo:
```diff
diff --git i/koappimage/Dockerfile w/koappimage/Dockerfile
index b10213b..ed95f07 100644
--- i/koappimage/Dockerfile
+++ w/koappimage/Dockerfile
@@ -1,13 +1,14 @@
 ARG REGISTRY=docker.io
-FROM scratch AS base
+FROM $REGISTRY/koreader/kobase:0.3.1-20.04 AS base
 
-FROM $REGISTRY/koreader/kobase:0.3.1-20.04 AS build
+FROM base AS build
 
-RUN sudo apt-get update
-RUN sudo apt-get upgrade -y
-RUN sudo apt-get install -y --no-install-recommends libsndio7.0
-RUN sudo apt-get clean
-RUN sudo rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
+USER root
+RUN apt-get update
+RUN apt-get upgrade -y
+RUN apt-get install -y --no-install-recommends libsndio7.0
+RUN apt-get clean
+RUN rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
 
 FROM base
 COPY --from=build / /
```

**Comment by benoit-pierre** [comment]
> Presumably that means these lines were accidentally left behind?
> 
> https://github.com/koreader/virdevenv/blob/dbf52c4c096228331ee151ad4c86202c8b6dadad/docker/ubuntu/kokobo/Dockerfile#L4-L6

Yep, and koremarkable.

**Review by benoit-pierre — APPROVED** [review]

**Pull request merged**
