### PR TITLE
factorize+rework image build

### PR DESCRIPTION
**Pull request by benoit-pierre**
The first commit simplify the make rules, with one central `Makefile` in `docker/ubuntu`:
```bash
# Usage
▹ make

USAGE

  TARGETS:
        make IMAGE            build image
        make IMAGE/shell      run interactive shell in image
        make IMAGE/push       push image to registry
        make prune            prune dangling images

  VARIABLES:
        USER                  repository name (e.g. koreader, default: bpierre)
        REGISTRY              remote registry to push too (default: docker.io)
        BASEIMAGE             default base image (default: koreader/kobase:0.3.4-20.04)

  IMAGES:
        baseimage-18.04
        baseimage-20.04
        baseimage-22.04
        baseimage-clang
        baseimage-python
        koandroid
        koappimage
        kobookeen
        kocervantes
        kodeb
        kokindle
        kokobo
        kopb
        koremarkable
        kout

# Build koappimage
▹ make koappimage
# Execute interactive shell in koappimage
▹ make koappimage/shell
```

When updating the `koappimage` image, to add SDL2 build dependencies, the result was a 1.5G image, much more than the expected ~900MB. It looks like I got the behavior of `COPY` wrong: https://github.com/moby/moby/issues/35280. At least depending on the storage backend. I did try the `containerd` backend, but the result image is still too big (~1.2G, even the base image is reported as bigger by `docker images`).

We can't use the build command `--squash` option because it's deprecated (`buildah` equivalent option does work fine).

So I reworked the build mechanism to automatically:
- setup a `build` stage prior to executing each image's `Dockerfile`
- and create a final from `scratch` layer, copying the result of the `build` stage, and setting up the default user / workdir

This work around both https://github.com/moby/moby/issues/35280 and https://github.com/moby/moby/issues/43614, since all layers are flattened. The disadvantage, is no layer sharing with the base image. ¯\\_(ツ)_/¯

With this mechanism, the updated `koappimage` size is 848MB.

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/virdevenv/105)

### CODE REVIEW

**Comment by benoit-pierre** [comment]
BTW, is it worth keeping the code for unused images :`baseimage-18.04`, `baseimage-22.04`, `baseimage-22.04`, `kobookeen`, and `kout`?

I noticed that `baseimage-22.04` is missing its `bashrc`.

**Comment by Frenzie** [comment]
18.04 was always intended to be dropped in time and the same goes for kobookeen and kout (although there was a chance they might be revived instead) but `22.04` is substantially different. It's the new version ready for migration, or at least it worked well enough when I last tested it. I don't recall otoh if there was much more to it than the gcc version and not having to compile gettext for my Lua patch, but the combination of not having to remember and being able to just swap it in is the general idea.

That doesn't mean it has to exist in its current form, but I would like to maintain that possibility. Quite the opposite of dropping it in fact because the time to think about 22.04 is now approaching. That would mean to migrate to 22.04, drop 20.04, and add 24.04 for testing.

**Comment by benoit-pierre** [comment]
> 18.04 was always intended to be dropped in time and the same goes for kobookeen and kout (although there was a chance they might be revived instead) but `22.04` is substantially different. It's the new version ready for migration, or at least it worked well enough when I last tested it. I don't recall otoh if there was much more to it than the gcc version and not having to compile gettext for my Lua patch, but the combination of not having to remember and being able to just swap it in is the general idea.
> 
> That doesn't mean it has to exist in its current form, but I would like to maintain that possibility. Quite the opposite of dropping it in fact because the time to think about 22.04 is now approaching. That would mean to migrate to 22.04, drop 20.04, and add 24.04 for testing.

When updating to 22.04, I would start from the current 20.04 `Dockerfile` anyway, which is why I don't really see the point in keeping the current code.

**Comment by Frenzie** [comment]
That's fair if it's become outdated. I hadn't planned any further development on the 20.04 base while I was the only one in this repo.

**Comment by Frenzie** [comment]
Btw @benoit-pierre @hius07 let me know if you'd like to be added to Liberapay. I don't think I asked. I'll ask @pazos and @poire-z again as well in case they changed their mind.

**Comment by poire-z** [comment]
(Thanks for asking again, but nope, I'm too old to change my mind :))

**Comment by hius07** [comment]
No, thank you, it's a pleasure and an honor to be a part of the team.

**Pull request merged**
