### PR TITLE
That's a typo combo all right

### PR DESCRIPTION
**Pull request by GeneralFailer**

### CODE REVIEW

**Comment by houqp** [comment]
oops, this is a critical bug!

**Comment by houqp** [comment]
Also, the relative path in `Vagrantfile` is probably out of date right now, you will need to add one more `..` to it for it to work. I forgot to update it after a refactoring.

**Comment by houqp** [comment]
The docker one is much faster compared to the vagrant vm. I haven't got time to write a readme for it yet. If you are familiar with docker, I recommend that one instead ;)

**Comment by GeneralFailer** [comment]
Yeah, I've just figured it out.

**Comment by GeneralFailer** [comment]
I thought you were talking about readme there for some reason.

**Pull request merged**
