### PR TITLE
baseimage-clang: fix build stage

### PR DESCRIPTION
**Pull request by benoit-pierre**
So we actually benefit from it (slightly reduced final image size).

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/virdevenv/92)

### CODE REVIEW

**Comment by Frenzie** [comment]
Incidentally, it seemed that while pushing it was sending over the full 960 MB? I found that a bit unexpected.

**Comment by benoit-pierre** [comment]
Which image?

**Comment by benoit-pierre** [comment]
koappimage? Because the size has ballooned:
```
koreader/koappimage       0.4.2-20.04   2f614d683e47   32 minutes ago   1.87GB
```
After pulling, vs:
```
benoitpierre/koappimage   0.4.2-20.04   4ba5693e0503   2 seconds ago    938MB
```
When building locally.

**Comment by benoit-pierre** [comment]
For reference, the base image:
```
koreader/kobase           0.3.1-20.04   0a7366ffc64f   28 hours ago     937MB
```

**Comment by benoit-pierre** [comment]
What do you get with `docker history`?
```bash
▸ docker history koreader/koappimage:0.4.2-20.04
IMAGE          CREATED        CREATED BY                                      SIZE      COMMENT
2f614d683e47   2 hours ago    /bin/sh -c #(nop) COPY dir:d2944404ec3b565fa…   937MB
<missing>      29 hours ago   WORKDIR /home/ko                                0B        buildkit.dockerfile.v0
<missing>      29 hours ago   USER ko                                         0B        buildkit.dockerfile.v0
<missing>      29 hours ago   COPY / / # buildkit                             937MB     buildkit.dockerfile.v0
▸ docker history benoitpierre/koappimage:0.4.2-20.04
IMAGE          CREATED             CREATED BY            SIZE      COMMENT
4ba5693e0503   About an hour ago   COPY / / # buildkit   1.57MB    buildkit.dockerfile.v0
<missing>      29 hours ago        WORKDIR /home/ko      0B        buildkit.dockerfile.v0
<missing>      29 hours ago        USER ko               0B        buildkit.dockerfile.v0
<missing>      29 hours ago        COPY / / # buildkit   937MB     buildkit.dockerfile.v0
▸ docker --version
Docker version 26.0.0, build 2ae903e86c
```

**Comment by benoit-pierre** [comment]
Same result after removing all images, cache, etc (`docker system prune -af` and rebuilding.

**Comment by Frenzie** [comment]
> What do you get with `docker history`?

Unsurprisingly, the same as the top one. Except for different hashes and creation times of course.

```
IMAGE          CREATED          CREATED BY                                      SIZE      COMMENT
197043cb2afc   25 minutes ago   /bin/sh -c #(nop) COPY dir:52d5b1f2e21073673…   937MB     
0a7366ffc64f   29 hours ago     WORKDIR /home/ko                                0B        buildkit.dockerfile.v0
<missing>      29 hours ago     USER ko                                         0B        buildkit.dockerfile.v0
<missing>      29 hours ago     COPY / / # buildkit                             937MB     buildkit.dockerfile.v0
```

**Comment by benoit-pierre** [comment]
Done.

**Comment by Frenzie** [comment]
Thanks. Otherwise GL would keep pulling twice what it needs to, and even though it's probably barely a blip for either party it'd get on my nerves. :-)

**Comment by Frenzie** [comment]
Annoyingly, that changed nothing. I'll stop worrying about it for the moment but I'm still puzzled.

```
$ docker images
REPOSITORY            TAG           IMAGE ID       CREATED          SIZE
koreader/koappimage   0.4.2-20.04   0a3773cf52da   10 seconds ago   1.87GB
```

```
$ docker history koreader/koappimage:0.4.2-20.04
IMAGE          CREATED              CREATED BY            SIZE      COMMENT
0a3773cf52da   About a minute ago   COPY / / # buildkit   937MB     buildkit.dockerfile.v0
<missing>      29 hours ago         WORKDIR /home/ko      0B        buildkit.dockerfile.v0
<missing>      29 hours ago         USER ko               0B        buildkit.dockerfile.v0
<missing>      29 hours ago         COPY / / # buildkit   937MB     buildkit.dockerfile.v0
```

```
$ docker --version
Docker version 26.0.1, build d260a54
```

**Pull request merged**
