### PR TITLE
Docker/Android: bump TC creation

### PR DESCRIPTION
**Pull request by Frenzie**
Cf. https://github.com/koreader/koreader/pull/5096

### CODE REVIEW

**Comment by pazos** [comment]
Looking the last failed build https://gitlab.com/koreader/nightly-builds/-/jobs/242868508 it seems that purging unused abis has no impact in launcher (which has restricted ndk abis in its build.gradle) but has impact in einkTest (which has no arch dependant code, but it is targeted as an universal apk)

We can restrict einkTest to armeabi-v7a since it is used on all eink devices out there or just leave the ndk without pruning.

**Comment by pazos** [comment]
Is ANDROID_HOME pointing to the sdk root folder? If not
`echo 'export ANDROID_HOME=/home/ko/android-sdk-linux' >>./.bashrc`

**Comment by Frenzie** [comment]
@pazos There is no last failed build per se. It's still pending, and has been for a few hours. (Business hours aren't good for the free plan. ;-D)

https://gitlab.com/koreader/nightly-builds/-/jobs/243118786

But indeed, it shouldn't matter. I think restricting eInktest is the way to go.

> just leave the ndk without pruning.

Meh, that's more than twice as large for no good reason.

**Comment by Frenzie** [comment]
@pazos It still seems to be trying to access it? Do I have to comment out the pruning? :-/

**Comment by Frenzie** [comment]
PS NDK r17 removes that specific arch https://developer.android.com/ndk/guides/abis#sa

**Comment by pazos** [comment]
> Create fake dir to silence gradle complaint

:man_facepalming:

**Comment by Frenzie** [comment]
But it works! :rofl:

**Pull request merged**
